version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ../src:/usr/src/app/src
      - /usr/src/app/node_modules
      - avatars_volume:/usr/src/app/avatars # Here we create a named volume for avatars
  db:
    image: postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  avatars_volume: # This declares the volume within the Docker compose file