version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ../src:/usr/src/app/src
      - /usr/src/app/node_modules
      - avatars_volume:/avatars # Here we create a named volume for avatars
      - wordsImages_volume:/wordsImages # Here we create a named volume for avatars

  db:
    image: postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      - "${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWORD}"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  avatars_volume: # This declares the volume within the Docker compose file
  wordsImages_volume: # This declares the volume within the Docker compose file
